# Angabe der Template-Version
AWSTemplateFormatVersion: '2010-09-09'
# Beschreibung, was das Cloudformation Template bauen soll
Description: 'Das ist die Darstellung der Grundstruktur eines Cloudformation Templates'

# Resources: PFLICHT! 
# Was soll erstellt werden?
Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH access
      VpcId: vpc-03050b3b62d2c30f7
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  # EC2-Instanz
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-089a7a2a13629ecc4 
      InstanceType: t3.micro
      SecurityGroupIds:
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: MeineErsteInstanz
        - Key: Owner
          Value: Me
  # VPC
  # SG
  # Subnets 
  # ...

# Outputs: Ausgabewerte (Optional)
# Was soll nach Ausführen des Templates zurückgegeben werden?
# Outputs:

# Weitere Sachen
# Mappings: Key-Value MAps (Optional)
# Conditions: If-then-Logik (optional)
# Metadata: Zusätzliche Infos (optional)